#define MOTOR_CONTROLLER_ADDRESS 0x04

#define COMMAND_HEARTBEAT	0x01
#define COMMAND_SETACCELERATION	0x02
#define COMMAND_GOVELOCITY	0x03
#define COMMAND_GOPOSITION	0x04
#define COMMAND_BRAKE	0x05
#define COMMAND_COAST	0x06

#define COMMAND_REPORTENCODER 0x10
#define COMMAND_REPORTSTANDBY 0x11

#define COMMAND_SETACCELERATION_LENGTH 8